// Internal demo, not shipped (scripts/ is outside the package `files`). Renders the three review
// surfaces (sticky, review-object body, inline comments) from the committed fixtures into one
// <details>-sectioned document — a living reference for how the templates render with every field
// present. Prints to stdout; CI appends it to the run's job summary. Run with `npx tsx scripts/preview.ts`.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Validation } from "io-ts";
import { render, isConvergenceRound, isReviewVerdict } from "../src/render.js";
import { buildInlineComments } from "../src/inline.js";
import {
  reviewBodyPointer,
  buildConvergence,
  computeCodeCounts,
  findingsPointer,
  DEFAULT_CONVERGENCE_THRESHOLD,
} from "../src/surface.js";
import { formatUtc } from "../src/format.js";
import {
  FindingsCodec,
  ResultEnvelopeCodec,
  PriceMapCodec,
  TestSummaryCodec,
} from "../src/schema.js";
import type { InlineComment } from "../src/types.js";

const root = resolve(import.meta.dirname, "..");
const fx = (name: string): string => resolve(root, "test/fixtures", name);
const REVIEWED_SHA = "1a2b3c4d5e6f70819aabbccddeeff00112233445";
// One fixture URL for both surfaces, so the reference cannot show them disagreeing.
const PREVIEW_RUN_URL = "https://github.com/owner/repo/actions/runs/7";

const orThrow = <A>(v: Validation<A>, what: string): A => {
  if (v._tag === "Left") throw new Error(`preview: invalid ${what} fixture`);
  return v.right;
};

const readJSON = (path: string): unknown => JSON.parse(readFileSync(path, "utf-8")) as unknown;

const inlineSection = (c: InlineComment): string =>
  `\n**\`${c.path}:${String(c.line)}\`**\n\n${c.body}\n\n---`;

const buildPreviewDoc = (
  sticky: string,
  reviewBody: string,
  comments: readonly InlineComment[],
): string =>
  `<!-- code-review:preview — rendered from fixtures; not a real review -->
## 🎨 Template preview — rendered from fixtures

How the three review surfaces render with every field present (a \`suggestion\`, the \`\`\`patch fallback, an out-of-diff stray, a recommendation, a systemic problem, the test panel, and a recomputed cost). Generated by \`scripts/preview.ts\` — **not a real review**. Post-time touches that \`code-review post\` adds (the inline-disposition line, real model names, blank-line collapsing, cross-links) are not shown here.

<details>
<summary><b>① Sticky summary comment</b> — <code>templates/comment.eta</code></summary>

${sticky}

</details>

<details>
<summary><b>② Review-object body</b> — built in <code>src/post.ts</code> (findings-json marker + pointer)</summary>

${reviewBody}

</details>

<details>
<summary><b>③ Inline review comments</b> — <code>templates/inline.eta</code>, one per in-diff finding</summary>
${comments.map(inlineSection).join("\n")}

</details>
`;

const findings = orThrow(FindingsCodec.decode(readJSON(fx("preview.findings.json"))), "findings");
const envelope = orThrow(
  ResultEnvelopeCodec.decode(readJSON(fx("sample-envelope.json"))),
  "envelope",
);
const prices = orThrow(PriceMapCodec.decode(readJSON(fx("preview.prices.json"))), "prices");
const testReport = orThrow(
  TestSummaryCodec.decode(readJSON(fx("preview.testreport.json"))),
  "test report",
);
const diff = readFileSync(fx("sample.diff"), "utf-8");

const { comments, strays } = buildInlineComments(findings.findings, diff, {
  inlineTemplate: readFileSync(resolve(root, "templates/inline.eta"), "utf-8"),
  findings,
});

// Mirror post's isRound: only a completed full-review run stamps convergence. The fixture is rendered
// as such (explicit route), with its own findings as round 1 — so the reference demonstrates the badge
// AND the trajectory together, exactly as a real round-1 sticky would.
const isFullReviewRound =
  isConvergenceRound("full review", false) && isReviewVerdict(findings.verdict);
const stampedFindings = isFullReviewRound
  ? {
      ...findings,
      convergence: buildConvergence(
        findings,
        DEFAULT_CONVERGENCE_THRESHOLD,
        [],
        1,
        computeCodeCounts(findings.findings, findings.systemic_problems ?? []),
        REVIEWED_SHA,
      ),
    }
  : findings;

// The marker names the findings artifact, built ONCE and shared by the sticky and the review body
// exactly like post. The preview has no real run, so this is a representative artifact URL.
const marker = findingsPointer(
  "https://api.github.com/repos/owner/repo/actions/artifacts/1234567890/zip",
);

// A representative `cloc --git --diff base head` table (issue #182) — in production the pipeline
// captures this; the fixture supplies one so the reference demonstrates the cloc collapsible.
const previewClocDiff = [
  "github.com/AlDanial/cloc v 1.98",
  "-------------------------------------------------------------------------------",
  "Language                     files          blank        comment           code",
  "-------------------------------------------------------------------------------",
  "TypeScript",
  " added                           2              6             18            240",
  " removed                         1              2              9             80",
  "Markdown",
  " added                           1              1              0             30",
  " removed                         0              0              0              0",
  "-------------------------------------------------------------------------------",
].join("\n");

const sticky = render({
  findings: stampedFindings,
  envelope,
  prices,
  pricesProvided: true,
  template: readFileSync(resolve(root, "templates/comment.eta"), "utf-8"),
  route: "full review",
  reviewedSha: REVIEWED_SHA,
  // The reference render must show the production shape: every production sticky carries the
  // stray permalinks, so the preview does too (issue #231 r1).
  repo: "owner/repo",
  testReport,
  clocDiff: previewClocDiff,
  strays,
  findingsPointer: marker,
  runUrl: PREVIEW_RUN_URL,
  postedAt: formatUtc(new Date()),
  pricedAt: new Date(),
});

const reviewBody = reviewBodyPointer(REVIEWED_SHA, undefined, PREVIEW_RUN_URL, true);

process.stdout.write(buildPreviewDoc(sticky, reviewBody, comments));
