// Internal demo, not shipped (scripts/ is outside the package `files`). Renders the three review
// surfaces (sticky, review-object body, inline comments) from the committed fixtures into one
// <details>-sectioned document — a living reference for how the templates render with every field
// present. Prints to stdout; CI appends it to the run's job summary. Run with `npx tsx scripts/preview.ts`.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Validation } from "io-ts";
import { render } from "../src/render.js";
import { buildInlineComments } from "../src/inline.js";
import { findingsPointer, reviewBodyPointer } from "../src/surface.js";
import { formatUtc } from "../src/format.js";
import {
  FindingsCodec,
  ResultEnvelopeCodec,
  PriceMapCodec,
  TestSummaryCodec,
} from "../src/schema.js";
import type { InlineComment } from "../src/types.js";

const root = resolve(import.meta.dirname, "..");
const fx = (name: string): string => resolve(root, "test/fixtures", name);
const REVIEWED_SHA = "1a2b3c4d5e6f70819aabbccddeeff00112233445";

const orThrow = <A>(v: Validation<A>, what: string): A => {
  if (v._tag === "Left") throw new Error(`preview: invalid ${what} fixture`);
  return v.right;
};

const readJSON = (path: string): unknown => JSON.parse(readFileSync(path, "utf-8")) as unknown;

const inlineSection = (c: InlineComment): string =>
  `\n**\`${c.path}:${String(c.line)}\`**\n\n${c.body}\n\n---`;

const buildPreviewDoc = (
  sticky: string,
  reviewBody: string,
  comments: readonly InlineComment[],
): string =>
  `<!-- code-review:preview — rendered from fixtures; not a real review -->
## 🎨 Template preview — rendered from fixtures

How the three review surfaces render with every field present (a \`suggestion\`, the \`\`\`patch fallback, an out-of-diff stray, a recommendation, the test panel, and a recomputed cost). Generated by \`scripts/preview.ts\` — **not a real review**. Post-time touches that \`code-review post\` adds (the inline-disposition line, real model names, blank-line collapsing, cross-links) are not shown here.

<details>
<summary><b>① Sticky summary comment</b> — <code>templates/comment.eta</code></summary>

${sticky}

</details>

<details>
<summary><b>② Review-object body</b> — built in <code>src/post.ts</code> (findings-json marker + pointer)</summary>

${reviewBody}

</details>

<details>
<summary><b>③ Inline review comments</b> — <code>templates/inline.eta</code>, one per in-diff finding</summary>
${comments.map(inlineSection).join("\n")}

</details>
`;

const findings = orThrow(FindingsCodec.decode(readJSON(fx("preview.findings.json"))), "findings");
const envelope = orThrow(
  ResultEnvelopeCodec.decode(readJSON(fx("sample-envelope.json"))),
  "envelope",
);
const prices = orThrow(PriceMapCodec.decode(readJSON(fx("preview.prices.json"))), "prices");
const testReport = orThrow(
  TestSummaryCodec.decode(readJSON(fx("preview.testreport.json"))),
  "test report",
);
const diff = readFileSync(fx("sample.diff"), "utf-8");

const { comments, strays } = buildInlineComments(findings.findings, diff, {
  inlineTemplate: readFileSync(resolve(root, "templates/inline.eta"), "utf-8"),
  findings,
});

const sticky = render({
  findings,
  envelope,
  prices,
  pricesProvided: true,
  template: readFileSync(resolve(root, "templates/comment.eta"), "utf-8"),
  reviewedSha: REVIEWED_SHA,
  testReport,
  strays,
  postedAt: formatUtc(new Date()),
});

const reviewBody = reviewBodyPointer(REVIEWED_SHA, undefined, findingsPointer(findings, undefined));

process.stdout.write(buildPreviewDoc(sticky, reviewBody, comments));
