#!/usr/bin/env bash
# Render the three review surfaces from the committed preview fixtures into one
# <details>-sectioned markdown document — a living reference for how the templates render
# with every field present. Drives both a reference comment on the review PR and the CI
# job summary. Reference only: the fixtures are not a real review, and post-time touches
# that `code-review post` adds (inline-disposition line, real model names, blank-line
# collapsing, cross-links) are not reproduced here. Requires a built dist/ (CI builds it).
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fx="$root/test/fixtures"
sha="1a2b3c4d5e6f70819aabbccddeeff00112233445"
cli=(node "$root/dist/index.js")

sticky="$("${cli[@]}" render "$fx/preview.findings.json" \
  --usage "$fx/sample-envelope.json" \
  --prices "$fx/preview.prices.json" \
  --reviewed-sha "$sha" \
  --test-report "$fx/preview.testreport.json")"

inline_json="$("${cli[@]}" inline "$fx/preview.findings.json" --diff "$fx/sample.diff")"

# The findings-json pointer (AGENTS-STOP directive + marker) the commenter prepends to every
# surface; the review-object body is that pointer plus a one-line link to the sticky.
pointer="$(printf '%s\n' "$sticky" | grep -E '^<!-- (AGENTS: STOP|code-review:findings-json)')"
review_body="${pointer}

🤖 Automated code review for \`${sha:0:7}\` — see the summary comment for the verdict, walkthrough, and cost."

inline_sections="$(printf '%s' "$inline_json" | jq -r '.comments[] | "\n**`\(.path):\(.line)`**\n\n\(.body)\n\n---"')"

cat <<PREVIEW
<!-- code-review:preview — rendered from test/fixtures/preview.findings.json; not a real review -->
## 🎨 Template preview — rendered from fixtures

How the three review surfaces render with every field present (a \`suggestion\`, the \`\`\`patch fallback, an out-of-diff stray, a recommendation, the test panel, and a recomputed cost). Generated by \`scripts/preview.sh\` from \`test/fixtures/preview.findings.json\` — **not a real review**. Post-time touches that \`code-review post\` adds (the inline-disposition line, real model names, blank-line collapsing, cross-links) are not shown here.

<details>
<summary><b>① Sticky summary comment</b> — <code>templates/comment.eta</code></summary>

${sticky}

</details>

<details>
<summary><b>② Review-object body</b> — built in <code>src/post.ts</code> (findings-json marker + pointer)</summary>

${review_body}

</details>

<details>
<summary><b>③ Inline review comments</b> — <code>templates/inline.eta</code>, one per in-diff finding</summary>
${inline_sections}

</details>
PREVIEW
